/*
 Copyright 2016-present The Material Motion Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import Foundation
import IndefiniteObservable

/**
 A Spring can pull a value from an initial position to a destination using a physical simulation.

 This class defines the expected shape of a Spring for use in creating a Spring source.
 */
public final class Spring<T: Zeroable>: ViewInteraction {

  /** Creates a spring with the provided properties and an initial velocity of zero. */
  public convenience init<O: MotionObservableConvertible>(to destination: O, threshold: CGFloat, system: @escaping (SpringConfiguration<T>) -> MotionObservable<T>) where O.T == T {
    let initialVelocity = createProperty(withInitialValue: T.zero() as! T) as! O
    self.init(to: destination, initialVelocity: initialVelocity, threshold: threshold, system: system)
  }

  /** Creates a spring with the provided properties and an initial velocity. */
  public init<O1: MotionObservableConvertible, O2: MotionObservableConvertible>(to destination: O1,
              initialVelocity: O2,
              threshold: CGFloat,
              system: @escaping (SpringConfiguration<T>) -> MotionObservable<T>) where O1.T == T, O2.T == T {
    self.destination = destination.asStream()
    self.initialVelocity = initialVelocity.asStream()
    self.system = system

    self.threshold = createProperty(withInitialValue: threshold)
  }

  /** The destination value of the spring represented as a property. */
  public let destination: MotionObservable<T>

  /** The initial velocity of the spring represented as a stream. */
  public let initialVelocity: MotionObservable<T>

  /** The tension configuration of the spring represented as a property. */
  public let tension = createProperty(withInitialValue: defaultSpringTension)

  /** The friction configuration of the spring represented as a property. */
  public let friction = createProperty(withInitialValue: defaultSpringFriction)

  /** The value used when determining completion of the spring simulation. */
  public let threshold: ReactiveProperty<CGFloat>

  public var system: SpringSystem<T>

  /** The stream of values generated by this spring. */
  public func stream<O: MotionObservableConvertible>(withInitialValue: O) -> MotionObservable<T> where O.T == T {
    let configuration = SpringConfiguration(destination: destination,
                                            initialValue: withInitialValue.asStream(),
                                            initialVelocity: initialVelocity,
                                            tension: tension,
                                            friction: friction,
                                            threshold: threshold)
    return system(configuration)
  }

  public func add(to reactiveView: ReactiveUIView, withRuntime runtime: MotionRuntime) {
    if let castedSelf = self as? Spring<CGPoint> {
      let position = reactiveView.reactiveLayer.position
      runtime.add(castedSelf.stream(withInitialValue: position), to: position)
    }
  }
}

/** The default tension configuration. */
public let defaultSpringTension: CGFloat = 342

/** The default friction configuration. */
public let defaultSpringFriction: CGFloat = 30

/** A SpringConfiguration is meant for use by a SpringConnect implementation. */
public struct SpringConfiguration<T> {
  /** The destination value of the spring represented as a property. */
  public let destination: MotionObservable<T>

  /** The initial value of the spring represented as a property. */
  public let initialValue: MotionObservable<T>

  /** The initial velocity of the spring represented as a property. */
  public let initialVelocity: MotionObservable<T>

  /** The tension configuration of the spring represented as a property. */
  public let tension: ReactiveProperty<CGFloat>

  /** The friction configuration of the spring represented as a property. */
  public let friction: ReactiveProperty<CGFloat>

  /** The value used when determining completion of the spring simulation. */
  public let threshold: ReactiveProperty<CGFloat>
}
